<div class="pubitem">
	<span class="pubitem_title">Fluctuating synaptic conductances recreate <em>in-vivo</em>-like activity<br>in neocortical neurons</span><br><br>
	<span class="pubitem_authors">Alain Destexhe, Michael Rudolph, Jean-Marc Fellous, Terrence J. Sejnowski</span><br><br>
	<span class="pubitem_reference">Neurosci. 107: 13-24, 2001</span>
</div>

<div class="pubitem_links"><a href="https://drive.google.com/file/d/0BxWNHu-AOXGha1JyYU1nUjRpb0k/edit?usp=sharing" target="_blank"><img src="../img/iconPDF.png" border="0"></a></div>

<div style="clear:both;"></div>

<h3><span>Abstract</span></h3>

<p>To investigate the basis of the fluctuating activity present in neocortical neurons <em>in vivo</em>, we have
combined computational models with whole-cell recordings using the dynamic-clamp technique. A simplified
'point-conductance' model was used to represent the currents generated by thousands of stochastically-releasing
synapses. Synaptic activity was represented by two independent fast glutamatergic and GABAergic
conductances described by stochastic random-walk processes. An advantage of this approach is that
all the model parameters can be determined from voltage-clamp experiments. We show that the point-conductance
model captures the amplitude and spectral characteristics of the synaptic conductances during background
activity. To determine if it can recreate <em>in-vivo</em>-like activity, we injected this point-conductance
model into a single-compartment model, or in rat prefrontal cortical neurons <em>in vitro</em> using dynamic-clamp.
This procedure successfully recreated several properties of neurons intracellularly-recorded <em>in-vivo</em>,
such as a depolarized membrane potential, the presence of high-amplitude membrane potential fluctuations,
a low input resistance and irregular spontaneous firing activity. In addition, the point-conductance
model could simulate the enhancement of responsiveness due to background activity. We conclude that
many of the characteristics of cortical neurons <em>in vivo</em> can be explained by fast glutamatergic and
GABAergic conductances varying stochastically.</p>
